### PR TITLE
scripts/test-infra: provide PR base SHA to codecov

### PR DESCRIPTION
**Pull request by marquiz**
In the hopes that codecov will be properly showing and calculating the diff.

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
🤞🏽

**Comment by marquiz** [comment]
Let's wait for https://github.com/kubernetes/test-infra/pull/29385

**Review by fmuyassarov — COMMENTED** [review]
LGTM

**Comment by fmuyassarov** [comment]
> Let's wait for [kubernetes/test-infra#29385](https://github.com/kubernetes/test-infra/pull/29385)

sorry if asking naive question, but what's the relationship of this patch with ^?

**Comment by marquiz** [comment]
> sorry if asking naive question, but what's the relationship of this patch with ^?

See the codecov report:

> Merging [#1199](https://codecov.io/gh/kubernetes-sigs/node-feature-discovery/pull/1199?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=kubernetes-sigs) (https://github.com/kubernetes-sigs/node-feature-discovery/commit/32072dddf19410653dcca44df6c3a86bb23858ef) into [master](https://codecov.io/gh/kubernetes-sigs/node-feature-discovery/commit/611ed65e432c5dcdd54507ff996e33381ba0fe6c?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=kubernetes-sigs) (https://github.com/kubernetes-sigs/node-feature-discovery/commit/611ed65e432c5dcdd54507ff996e33381ba0fe6c) will increase coverage by 1.92%.

which refers to some very outdated commit as "master". The test-infra PR should meke sure that the master branch in codecov.io stays up to date and we get meaningful reports here

**Pull request merged**
