### PR TITLE
source/network: refactor readIfaceInfo

### PR DESCRIPTION
**Pull request by marquiz**
Make the function more generic and re-usable.

### CODE REVIEW

**Review by AhmedGrati — APPROVED** [review]
That sounds better! Thanks!

**Comment by marquiz** [comment]
@AhmedGrati feel free to lgtm if you think it's good to merge 😊

**Review by AhmedGrati — APPROVED** [review]

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
