### PR TITLE
NFD-Topology-Updater: Bump NRT API to version v0.0.12

### PR DESCRIPTION
**Pull request by swatisehgal**
The NodeResourceTopology API has been made cluster
scoped as in the current context a CR corresponds to
a Node and since Node is a cluster scoped resource it
makes sense to make NRT cluster scoped as well.

Ref: k8stopologyawareschedwg/noderesourcetopology-api#18

Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

### CODE REVIEW

**Review by marquiz — CHANGES_REQUESTED** [review]
Makes sense 👍 

Please also remove references to `master.topologyUpdaterNs` in  `docs/get-started/deployment-and-usage.md`

Otherwise good

**Comment by swatisehgal** [comment]
> Makes sense +1
> 
> Please also remove references to `master.topologyUpdaterNs` in `docs/get-started/deployment-and-usage.md`
> 
> Otherwise good

Done!

**Review by marquiz — APPROVED** [review]
Thanks @swatisehgal. I like this as it makes #618 obsolete 😊 
/lgtm

**Pull request merged**
