### PR TITLE
Switch to sigs.k8s.io/yaml

### PR DESCRIPTION
**Pull request by marquiz**
Replace github.com/ghodss/yaml.

### CODE REVIEW

**Comment by Ethyling** [comment]
Should we remove it in the go.mod too? Otherwise lgtm

**Comment by marquiz** [comment]
> Should we remove it in the go.mod too? Otherwise lgtm

Woops, I thought I had that 😬 Fixed

**Comment by Ethyling** [comment]
> > Should we remove it in the go.mod too? Otherwise lgtm
> 
> Woops, I thought I had that grimacing Fixed

Hum, seems like you did not push :smile:

**Comment by marquiz** [comment]
Oh my, what next 🤯 😄

**Pull request merged**
