### PR TITLE
Slight rework of building

### PR DESCRIPTION
**Pull request by marquiz**
Add build and install targets to Makefile and take use of that in the Dockerfile

### CODE REVIEW

**Comment by Ethyling** [comment]
Should we add the bin directory to gitignore and dockerignore?

**Comment by marquiz** [comment]
> Should we add the bin directory to gitignore and dockerignore?

Very good observation! Added. And rebased.

**Comment by Ethyling** [comment]
Need to be rebased to pass the CI (to have the fix in the usb custom source) :smile:

**Comment by marquiz** [comment]
> Need to be rebased to pass the CI

Ha, rebased (thanks for the fix!)

**Comment by marquiz** [comment]
Rebased. I needed to add two variables in makefile to preserve separate hostmount prefix for local and container builds. Also added documentation for the new variables (hopefully those make sense)

**Comment by marquiz** [comment]
Rebased

**Pull request merged**
