### PR TITLE
Update k8s dependencies to 1.19.4

### PR DESCRIPTION
**Pull request by cynepco3hahue**
To prepare the repository to introduce new features, as topology-updater functionality we should use updated dependencies.

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Thanks a lot for this PR @cynepco3hahue ! I was personally struggling to achieve this , thanks for taking the time 
/ok-to-test

**Comment by cynepco3hahue** [comment]
@ArangoGutierrez yw :) I tested make targets `make`, `make e2e-test` and `make test`, the single failure that I have related to unittest
```
Failures:

  * /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go 
  Line 124:
  Expected: nil
  Actual:   'failed to connect: context deadline exceeded'
  goroutine 58 [running]:
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:143 +0x6f
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:103 +0x71
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:176 +0xe6
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:125 +0x66
  sigs.k8s.io/node-feature-discovery/pkg/nfd-worker_test.TestRunTls.func1.1.1()
        /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go:124 +0x59
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x24
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x125
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:163 +0x48
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x462
  github.com/jtolds/gls.EnsureGoroutineId(0xc0003a1530)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0x11d
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0001f14d0, 0xc0003a14d0, 0xc00039eee0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x153
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:162 +0x1c8
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:77 +0x92
  sigs.k8s.io/node-feature-discovery/pkg/nfd-worker_test.TestRunTls.func1.1()
        /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go:123 +0x39d
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x24
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x125
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:163 +0x48
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x462
  github.com/jtolds/gls.EnsureGoroutineId(0xc00060e420)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0x11d
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0001f14d0, 0xc00060e3c0, 0xc0006901a0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x153
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:162 +0x1c8
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:77 +0x92
  sigs.k8s.io/node-feature-discovery/pkg/nfd-worker_test.TestRunTls.func1()
        /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go:112 +0x7a
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x24
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x125
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:110 +0xf0
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x462
  github.com/jtolds/gls.EnsureGoroutineId.func1()
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc000690180)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc000690180)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc00060e300)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xfd
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0001f14d0, 0xc00060e2a0, 0xc000690140)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x153
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:105 +0x231
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:75 +0xbe
  sigs.k8s.io/node-feature-discovery/pkg/nfd-worker_test.TestRunTls(0xc000602600)
        /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go:111 +0x358
  testing.tRunner(0xc000602600, 0x170d048)
        /usr/local/go/src/testing/testing.go:1127 +0xef
  created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1178 +0x386
  


50 total assertions

--- FAIL: TestRunTls (60.00s)
FAIL
FAIL    sigs.k8s.io/node-feature-discovery/pkg/nfd-worker       60.031s
```

but I checked the same test under the master and had the same issue. Probably it deserved the issue, WDT?

**Comment by ArangoGutierrez** [comment]
I have been working on this on the side, and is a real pain, as you might notice, bc some dependencies changed a lot. I will test this locally and provide comments, so far looks good to me. 
the good thing is that the prow test for `make image` succeeded and that internally runs `make test`, so we are almost there

**Comment by marquiz** [comment]
> I tested make targets `make`, `make e2e-test` and `make test`, the single failure that I have related to unittest

That is caused by Golang v1.15. We should open 

> Probably it deserved the issue, WDT?

Yeah, that needs to be fixed. A separate issue would be good

**Comment by marquiz** [comment]
Thanks @cynepco3hahue for this PR!
/approve

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by cynepco3hahue** [comment]
@marquiz Done - https://github.com/kubernetes-sigs/node-feature-discovery/issues/387

**Pull request merged**
