### PR TITLE
chore: combine cpu count and thread_siblings functions into discover topology function

### PR DESCRIPTION
**Pull request by AhmedGrati**
See https://github.com/kubernetes-sigs/node-feature-discovery/pull/1497#discussion_r1426426249

### CODE REVIEW

**Comment by AhmedGrati** [comment]
ping @marquiz

**Comment by marquiz** [comment]
Thanks @AhmedGrati for the PR! Will look at closer when the v0.15 is out
/milestone v0.16

**Review by marquiz — APPROVED** [review]
Thanks @AhmedGrati for contribution. Looks good to me

**Pull request merged**
