### PR TITLE
Increase allowed image build timeout for 500s

### PR DESCRIPTION
**Pull request by fmuyassarov**
Image build is failing otherwise as per discussion on https://github.com/kubernetes-sigs/node-feature-discovery/pull/935#issuecomment-1292504879.
/cc @marquiz

### CODE REVIEW

**Comment by fmuyassarov** [comment]
@marquiz do you have an access to rerun the failed job from [Prow UI](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-node-feature-discovery-push-images/1585181601254346752) ?

**Review by marquiz — APPROVED** [review]
Thanks @fmuyassarov for the update. I hope this will stop sporadic (and really rare) timeouts in image building

**Comment by marquiz** [comment]
> @marquiz do you have an access to rerun the failed job from [Prow UI](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-node-feature-discovery-push-images/1585181601254346752) ?

I don't, unfortunately

**Pull request merged**
