### PR TITLE
pkg/api/feature: small improvements

### PR DESCRIPTION
**Pull request by marquiz**
Slight improvements on the internal pkg/api/feature api.
- use pointers of structs:
  Make it easier to mutate the feature sets.
- generator functions with initial values:
  Flavor the generator helper functions with arguments for specifying the
set of features to put into the generated objects.

### CODE REVIEW

**Comment by marquiz** [comment]
Missed one func
/hold

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
