### PR TITLE
Use release v0.6.0 in deployment templates and README

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
Preparing for next release

/hold

**Comment by marquiz** [comment]
I'm ready for this 🤞 

/unhold

**Comment by adrianchiris** [comment]
Hi, is there a time table for nfd release ?
Working on some exciting stuff that utilizes the latest and greatest features of NFD :)

**Comment by marquiz** [comment]
> Hi, is there a time table for nfd release ?

Just waiting for a small prod from others 👉 😉 ping @zvonkok @Ethyling

**Comment by zvonkok** [comment]
/lgtm 
As written in the issue all needed PRs from my side are merged.

**Pull request merged**
