### PR TITLE
docs: deprecation policy for Helm chart params

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Review by adrianchiris — APPROVED** [review]

**Review by ArangoGutierrez — APPROVED** [review]
I agree given that past 2 releases some flag or CRD could have changed enough.

**Comment by marquiz** [comment]
Thx for the review. We could go with this and adjust later if needed
/unhold

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
