### PR TITLE
README: update the outdated usage demo

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
Feedback on the demo content is welcome, too 😄

**Comment by marquiz** [comment]
It's basically a "re-make" of the old demo.

**Comment by Ethyling** [comment]
Looks good to be, but I will let some time if someone wants to add something

**Comment by marquiz** [comment]
That was quite quickly put together. I'll enhance it in the future in any case, but, prolly in another PR (unless there's thumbs down for this)

**Pull request merged**
