### PR TITLE
docs: simplify quick-start page

### PR DESCRIPTION
**Pull request by marquiz**
Move topology-updater deployment notes to the topology-updater usage page. Also, rework the plaintext and headings a bit.

### CODE REVIEW

**Comment by marquiz** [comment]
ping @Tal-or @fromanirh touching the topology-updater documentation

**Review by fromanirh — COMMENTED** [review]
LGTM
leaving the final ack to @Tal-or

**Comment by marquiz** [comment]
Thanks @fromanirh 

Rebased to resolved conflicts

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by marquiz** [comment]
@Tal-or this got merged a bit hastily but please see if you have any comments and I can address those

**Comment by Tal-or** [comment]
Thank you @marquiz it LGTM no additional changes are needed

**Pull request merged**
