### PR TITLE
Switch to using go modules

### PR DESCRIPTION
**Pull request by marquiz**
Update go version in Docker build image to v1.12.

### CODE REVIEW

**Comment by zvonkok** [comment]
/lgtm Any plans to support disconnected environments by using the `vendor` directory? 
`go mod vendor`

**Comment by marquiz** [comment]
/lgtm


> Any plans to support disconnected environments by using the `vendor` directory?

I haven't had any plans for that

**Comment by marquiz** [comment]
> @marquiz: you cannot LGTM your own PR.

@zvonkok @kad @Ethyling  could you give a hand?

**Pull request merged**
