### PR TITLE
WIP: Test if buildx is enabled at Prow

### LINKED ISSUE #426: Add support for arm64, armV7, armV8
**What would you like to be added**:
There is no _arm_ support. It would be good to see support this for those architectures.

**Why is this needed**:
Getting "standard_init_linux.go:219: exec user process caused: exec format error" for pods scheduled on _arm_ nodes.
Usually it's easy to do - just making image multi-architecture =)

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Fixes #426 

THIS IS A WIP PR, TO TEST PROW FUNCTIONALITY TOWARDS DOCKER BUILDX

> DO NOT LGTM OR MERGE

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
@marquiz how do you wanna move forward with this initiative?

**Comment by marquiz** [comment]
> @marquiz how do you wanna move forward with this initiative?

Does this work? 😉 
/retest

When/if image building passes you can start working on the makefile. We should probably have `ARCH` or smth as a Makefile variable. And prolly only use buildx if `ARCH` has been set ,i.e. do a native build by default.

**Comment by ArangoGutierrez** [comment]
let's add this to V0.11 milestone

**Comment by ArangoGutierrez** [comment]
in lieu of #698 
/close

**Pull request closed without merging**
