### PR TITLE
topology-gc: move initial GC out of startNodeInformer()

### PR DESCRIPTION
**Pull request by marquiz**
Small refactor. Contextually this feels more like under periodicGC().

### CODE REVIEW

**Comment by marquiz** [comment]
Depends on #1307 
/hold

**Comment by marquiz** [comment]
#1307 merged
/unhold
/assign @PiotrProkop

**Comment by marquiz** [comment]
Woops, #1307 not merged yet 🙈
/hold

**Comment by PiotrProkop** [comment]
Yeah, looks better 😄 will add label after https://github.com/kubernetes-sigs/node-feature-discovery/pull/1307 is merged.

**Comment by marquiz** [comment]
OK, now #1307 is merged (and this one rebased)
/unhold

**Comment by marquiz** [comment]
ping @PiotrProkop

**Pull request merged**
