### PR TITLE
go.mod: bump kubernetes to v1.31

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
Perhaps we better wait for https://github.com/kubernetes-sigs/controller-runtime/issues/2925 ?

**Comment by fmuyassarov** [comment]
> Perhaps we better wait for [kubernetes-sigs/controller-runtime#2925](https://github.com/kubernetes-sigs/controller-runtime/issues/2925) ?

related slack chat: https://app.slack.com/client/T09NY5SBT/CHGFYJVAN

**Comment by marquiz** [comment]
Yeah, maybe I was A BIT hasty with this one :relaxed: I think this needs to wait until the gRPC stuff is dropped (to get rid of the linter deprecation warnings)

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by marquiz** [comment]
@ArangoGutierrez PTAL

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
