### PR TITLE
Move testdata to root

### PR DESCRIPTION
**Pull request by elezar**
Go mod automatically ignores the /testdata directory. This change ensures that the rootfs for source/pci tests are not included in the module definition.

This replaces #1919

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
PR https://github.com/elezar/node-feature-discovery/pull/1 fixes tests

**Review by ArangoGutierrez — APPROVED** [review]
I'll leave the lgtm to @marquiz

**Comment by ArangoGutierrez** [comment]
/milestone-v0.17

**Comment by elezar** [comment]
@ArangoGutierrez @marquiz given that this *should* address issues in importing the API and client packages could this also be backported to the v0.16.x branch?

**Pull request merged**
