### PR TITLE
github: small fix in new-release issue template

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
we will hopefully soon talk about 1.x, so I am not sold into hardcoding it like 0.major right?

**Comment by marquiz** [comment]
`0.$MAJ` is used elsewhere in this template so I'd suggest to use it for now. Let's update the template if we ever get to 1.0 😎 Looking at the pace of improvements/contributions of the past few months we're not reaching 1.0 anytime soon...

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
