### PR TITLE
go.mod: bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4

### PR DESCRIPTION
**Pull request by marquiz**
Supersedes #1342

### CODE REVIEW

**Comment by jjacobelli** [comment]
@marquiz I think there is a small issue in the commit message: `go.mod; ...` => `go.mod: ...` (`;` instead of `:`)

**Comment by marquiz** [comment]
/retitle go.mod: bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4

**Comment by marquiz** [comment]
> @marquiz I think there is a small issue in the commit message: `go.mod; ...` => `go.mod: ...` (`;` instead of `:`)

Fixed. Blame my old eyes and small font size 🙈

**Pull request merged**
