### PR TITLE
release-0.8: update references to point to v0.8.0

### PR DESCRIPTION
**Pull request by marquiz**
Generated with:

```
scripts/prepare-release.sh v0.8.0
```

### CODE REVIEW

**Comment by marquiz** [comment]
Want to sleep over this 😉 
/hold

**Review by ArangoGutierrez — APPROVED** [review]
LGTM

**Review by e0ne — APPROVED** [review]

**Comment by marquiz** [comment]
Let's give it a try
/unhold

**Comment by marquiz** [comment]
Should've tested helm repo update on the main repo and not just my personal clone 🤦 
https://github.com/kubernetes-sigs/node-feature-discovery/pull/486

**Pull request merged**
