### PR TITLE
Disable armv7 builds 

### PR DESCRIPTION
**Pull request by ArangoGutierrez**

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
@Links2004 unfortunately the armv7 builds fail and we need to disable them

```
#25 [linux/arm/v7 builder 5/7] RUN go mod download
#25 148.8 go: cloud.google.com/go/compute@v1.23.3: Get "https://proxy.golang.org/cloud.google.com/go/compute/@v/v1.23.3.mod": net/http: TLS handshake timeout
#25 ERROR: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
```

Happens locally and in the CI.

/retest
/lgtm

**Comment by Links2004** [comment]
@marquiz this sounds more like a network problem then a armv7 problem will try locally

**Comment by marquiz** [comment]
@ArangoGutierrez could you change the commit message title to explicitly state that we disable armv7?
/remove lgtm

**Comment by Links2004** [comment]
did a local run, and its working on 2 of 2 my machines.
`net/http: TLS handshake timeout` hints a network problem but since I have no idea about the build infrastrucure used its hard to say where the problem is.

my system:
```
OS: uptodate Arch

$ docker --version
Docker version 26.1.0, build 9714adc6c7

$ docker buildx version
github.com/docker/buildx 0.14.0 171fcbeb69d67c90ba7f44f41a9e418f6a6ec1da

$ qemu-arm-static --version
qemu-arm version 8.2.2
```

build logs:
```
$ make push-all
./hack/init-buildx.sh
namespace: node-feature-discovery
image: registry.k8s.io/nfd/node-feature-discovery:v0.16.0-devel-190-g21b624b4
DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 --progress=auto --pull --push --build-arg VERSION=v0.16.0-devel-190-g21b624b4 --build-arg HOSTMOUNT_PREFIX=/host- --build-arg BUILDER_IMAGE=golang:1.22-bookworm --build-arg BASE_IMAGE_FULL=debian:bookworm-slim --build-arg BASE_IMAGE_MINIMAL=scratch --target full -t registry.k8s.io/nfd/node-feature-discovery:v0.16.0-devel-190-g21b624b4-full   ./
[+] Building 273.5s (33/39)                                                                                docker-container:nfd-builder
 => [linux/amd64 builder 5/7] RUN go mod download                                                                                 12.6s
 => [linux/arm64 builder 5/7] RUN go mod download                                                                                 21.8s
 => [linux/arm/v7 builder 2/7] COPY go.mod go.sum /go/node-feature-discovery/                                                      5.9s
 => [linux/arm/v7 builder 3/7] COPY api/nfd/go.mod api/nfd/go.sum /go/node-feature-discovery/api/nfd/                              0.6s
 => [linux/amd64 builder 6/7] COPY . /go/node-feature-discovery                                                                    0.6s
 => [linux/amd64 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                        33.1s
 => [linux/arm/v7 builder 4/7] WORKDIR /go/node-feature-discovery                                                                  0.3s
 => [linux/arm/v7 builder 5/7] RUN go mod download                                                                                29.5s
 => [linux/arm64 builder 6/7] COPY . /go/node-feature-discovery                                                                    1.6s
 => [linux/arm64 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                       246.2s
 => => # k8s.io/apiserver/pkg/server/dynamiccertificates                                                                               
 => => # k8s.io/apiserver/plugin/pkg/authorizer/webhook                                                                                
 => => # k8s.io/client-go/informers/policy                                                                                             
 => => # k8s.io/apiserver/pkg/server/options/encryptionconfig                                                                          
 => => # k8s.io/apiserver/pkg/authorization/authorizerfactory                                                                          
 => => # k8s.io/apiserver/pkg/server/options/encryptionconfig/controller                                                               
 => [linux/arm/v7 builder 6/7] COPY . /go/node-feature-discovery                                                                   0.8s
[+] Building 273.6s (33/39)                                                                                docker-container:nfd-builder
 => [linux/amd64 builder 5/7] RUN go mod download                                                                                 12.6s
 => [linux/arm64 builder 5/7] RUN go mod download                                                                                 21.8s
 => [linux/arm/v7 builder 2/7] COPY go.mod go.sum /go/node-feature-discovery/                                                      5.9s
 => [linux/arm/v7 builder 3/7] COPY api/nfd/go.mod api/nfd/go.sum /go/node-feature-discovery/api/nfd/                              0.6s
 => [linux/amd64 builder 6/7] COPY . /go/node-feature-discovery                                                                    0.6s
 => [linux/amd64 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                        33.1s
 => [linux/arm/v7 builder 4/7] WORKDIR /go/node-feature-discovery                                                                  0.3s
 => [linux/arm/v7 builder 5/7] RUN go mod download                                                                                29.5s
 => [linux/arm64 builder 6/7] COPY . /go/node-feature-discovery                                                                    1.6s
 => [linux/arm64 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                       246.4s
 => => # k8s.io/apiserver/pkg/server/dynamiccertificates                                                                               
 => => # k8s.io/apiserver/plugin/pkg/authorizer/webhook                                                                                
 => => # k8s.io/client-go/informers/policy                                                                                             
 => => # k8s.io/apiserver/pkg/server/options/encryptionconfig                                                                          
 => => # k8s.io/apiserver/pkg/authorization/authorizerfactory                                                                          
 => => # k8s.io/apiserver/pkg/server/options/encryptionconfig/controller                                                               
 => [linux/arm/v7 builder 6/7] COPY . /go/node-feature-discovery                                                                   0.8s
[+] Building 273.8s (33/39)                                                                                docker-container:nfd-builder
 => [linux/amd64 builder 5/7] RUN go mod download                                                                                 12.6s
 => [linux/arm64 builder 5/7] RUN go mod download                                                                                 21.8s
 => [linux/arm/v7 builder 2/7] COPY go.mod go.sum /go/node-feature-discovery/                                                      5.9s
 => [linux/arm/v7 builder 3/7] COPY api/nfd/go.mod api/nfd/go.sum /go/node-feature-discovery/api/nfd/                              0.6s
 => [linux/amd64 builder 6/7] COPY . /go/node-feature-discovery                                                                    0.6s
 => [linux/amd64 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                        33.1s
 => [linux/arm/v7 builder 4/7] WORKDIR /go/node-feature-discovery                                                                  0.3s
 => [linux/arm/v7 builder 5/7] RUN go mod download                                                                                29.5s
 => [linux/arm64 builder 6/7] COPY . /go/node-feature-discovery                                                                    1.6s
 => [linux/arm64 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                       246.5s
 => => # k8s.io/apiserver/pkg/server/dynamiccertificates                                                                               
 => => # k8s.io/apiserver/plugin/pkg/authorizer/webhook                                                                                
 => => # k8s.io/client-go/informers/policy                                                                                             
 => => # k8s.io/apiserver/pkg/server/options/encryptionconfig                                                                          
 => => # k8s.io/apiserver/pkg/authorization/authorizerfactory                                                                          
 => => # k8s.io/apiserver/pkg/server/options/encryptionconfig/controller                                                               
 => [linux/arm/v7 builder 6/7] COPY . /go/node-feature-discovery                                                                   0.8s
[+] Building 481.0s (40/40) FINISHED                                                                        docker-container:nfd-builder
 => [internal] load build definition from Dockerfile                                                                                0.0s
 => => transferring dockerfile: 1.35kB                                                                                              0.0s
 => [linux/arm/v7 internal] load metadata for docker.io/library/debian:bookworm-slim                                                0.9s
 => [linux/arm/v7 internal] load metadata for docker.io/library/golang:1.22-bookworm                                                1.0s
 => [linux/arm64 internal] load metadata for docker.io/library/debian:bookworm-slim                                                 0.7s
 => [linux/amd64 internal] load metadata for docker.io/library/debian:bookworm-slim                                                 0.5s
 => [linux/arm64 internal] load metadata for docker.io/library/golang:1.22-bookworm                                                 0.6s
 => [linux/amd64 internal] load metadata for docker.io/library/golang:1.22-bookworm                                                 0.6s
 => [internal] load .dockerignore                                                                                                   0.1s
 => => transferring context: 66B                                                                                                    0.0s
 => [internal] load build context                                                                                                   0.3s
 => => transferring context: 923.12kB                                                                                               0.0s
 => [linux/arm/v7 builder 1/7] FROM docker.io/library/golang:1.22-bookworm@sha256:d0902bacefdde1cf45528c098d14e55d78c107def8a22d14  9.3s
 => => resolve docker.io/library/golang:1.22-bookworm@sha256:d0902bacefdde1cf45528c098d14e55d78c107def8a22d148eabd71582d7a99f       0.2s
 => => sha256:8f3625dd93044417b5a52b53d118a76652c8ba0598f515783b3a0060505179ca 175B / 175B                                          0.2s
 => => sha256:6fc2de4456c087cd0ac676074b442a07eafe9b76a46ed236fa0ff2e926f986c6 67.71MB / 67.71MB                                    1.9s
 => => sha256:6fa10c37916f11898cc1908f6eff64247201ba4a768880b8ed97e39e0f182b18 66.27MB / 66.27MB                                    2.0s
 => => sha256:38d07170ec327fa1117b5289697e5555f4c3ba76d00200d7c7cc5c143086856f 59.22MB / 59.22MB                                    2.4s
 => => sha256:52886721ea5a8a8bac2b197dccd42a74948b88bedcfe0fdf8b24e234c0a660d0 21.95MB / 21.95MB                                    1.3s
 => => sha256:80e84b3257949a283234599e3906626cfb4ff482d06fa4dc3eaf1dd36551dafa 45.17MB / 45.17MB                                    1.5s
 => => extracting sha256:80e84b3257949a283234599e3906626cfb4ff482d06fa4dc3eaf1dd36551dafa                                           0.7s
 => => extracting sha256:52886721ea5a8a8bac2b197dccd42a74948b88bedcfe0fdf8b24e234c0a660d0                                           0.3s
 => => extracting sha256:38d07170ec327fa1117b5289697e5555f4c3ba76d00200d7c7cc5c143086856f                                           1.0s
 => => extracting sha256:6fa10c37916f11898cc1908f6eff64247201ba4a768880b8ed97e39e0f182b18                                           0.7s
 => => extracting sha256:6fc2de4456c087cd0ac676074b442a07eafe9b76a46ed236fa0ff2e926f986c6                                           2.3s
 => => extracting sha256:8f3625dd93044417b5a52b53d118a76652c8ba0598f515783b3a0060505179ca                                           0.1s
 => => extracting sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1                                           0.1s
 => [linux/arm/v7 full 1/3] FROM docker.io/library/debian:bookworm-slim@sha256:155280b00ee0133250f7159b567a07d7cd03b1645714c3a7458  2.0s
 => => resolve docker.io/library/debian:bookworm-slim@sha256:155280b00ee0133250f7159b567a07d7cd03b1645714c3a7458b2287b0ca83cb       0.3s
 => => sha256:77e415c4e7c678efbc2cc774d4bc05f6f2de2a2e04959d7e324ce092026c650e 24.74MB / 24.74MB                                    0.7s
 => => extracting sha256:77e415c4e7c678efbc2cc774d4bc05f6f2de2a2e04959d7e324ce092026c650e                                           0.8s
 => CACHED [linux/arm64 full 1/3] FROM docker.io/library/debian:bookworm-slim@sha256:155280b00ee0133250f7159b567a07d7cd03b1645714c  0.4s
 => => resolve docker.io/library/debian:bookworm-slim@sha256:155280b00ee0133250f7159b567a07d7cd03b1645714c3a7458b2287b0ca83cb       0.3s
 => CACHED [linux/arm64 builder 1/7] FROM docker.io/library/golang:1.22-bookworm@sha256:d0902bacefdde1cf45528c098d14e55d78c107def8  0.4s
 => => resolve docker.io/library/golang:1.22-bookworm@sha256:d0902bacefdde1cf45528c098d14e55d78c107def8a22d148eabd71582d7a99f       0.2s
 => CACHED [linux/amd64 full 1/3] FROM docker.io/library/debian:bookworm-slim@sha256:155280b00ee0133250f7159b567a07d7cd03b1645714c  0.4s
 => => resolve docker.io/library/debian:bookworm-slim@sha256:155280b00ee0133250f7159b567a07d7cd03b1645714c3a7458b2287b0ca83cb       0.3s
 => CACHED [linux/amd64 builder 1/7] FROM docker.io/library/golang:1.22-bookworm@sha256:d0902bacefdde1cf45528c098d14e55d78c107def8  0.4s
 => => resolve docker.io/library/golang:1.22-bookworm@sha256:d0902bacefdde1cf45528c098d14e55d78c107def8a22d148eabd71582d7a99f       0.2s
 => [linux/arm64 builder 2/7] COPY go.mod go.sum /go/node-feature-discovery/                                                        0.5s
 => [linux/amd64 builder 2/7] COPY go.mod go.sum /go/node-feature-discovery/                                                        0.4s
 => [linux/amd64 builder 3/7] COPY api/nfd/go.mod api/nfd/go.sum /go/node-feature-discovery/api/nfd/                                1.0s
 => [linux/arm64 builder 3/7] COPY api/nfd/go.mod api/nfd/go.sum /go/node-feature-discovery/api/nfd/                                1.0s
 => [linux/amd64 builder 4/7] WORKDIR /go/node-feature-discovery                                                                    0.6s
 => [linux/arm64 builder 4/7] WORKDIR /go/node-feature-discovery                                                                    0.6s
 => [linux/amd64 builder 5/7] RUN go mod download                                                                                  12.6s
 => [linux/arm64 builder 5/7] RUN go mod download                                                                                  21.8s
 => [linux/arm/v7 builder 2/7] COPY go.mod go.sum /go/node-feature-discovery/                                                       5.9s
 => [linux/arm/v7 builder 3/7] COPY api/nfd/go.mod api/nfd/go.sum /go/node-feature-discovery/api/nfd/                               0.6s
 => [linux/amd64 builder 6/7] COPY . /go/node-feature-discovery                                                                     0.6s
 => [linux/amd64 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                         33.1s
 => [linux/arm/v7 builder 4/7] WORKDIR /go/node-feature-discovery                                                                   0.3s
 => [linux/arm/v7 builder 5/7] RUN go mod download                                                                                 29.5s
 => [linux/arm64 builder 6/7] COPY . /go/node-feature-discovery                                                                     1.6s
 => [linux/arm64 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                        389.4s
 => [linux/arm/v7 builder 6/7] COPY . /go/node-feature-discovery                                                                    0.8s
 => [linux/arm/v7 builder 7/7] RUN make install VERSION=v0.16.0-devel-190-g21b624b4 HOSTMOUNT_PREFIX=/host-                       419.2s
 => [linux/amd64 full 2/3] COPY --from=builder /go/node-feature-discovery/deployment/components/worker-config/nfd-worker.conf.exam  0.2s
 => [linux/amd64 full 3/3] COPY --from=builder /go/bin/* /usr/bin/                                                                  1.0s
 => [linux/arm64 full 2/3] COPY --from=builder /go/node-feature-discovery/deployment/components/worker-config/nfd-worker.conf.exam  0.2s
 => [linux/arm64 full 3/3] COPY --from=builder /go/bin/* /usr/bin/                                                                  1.0s
 => [linux/arm/v7 full 2/3] COPY --from=builder /go/node-feature-discovery/deployment/components/worker-config/nfd-worker.conf.exa  0.2s
 => [linux/arm/v7 full 3/3] COPY --from=builder /go/bin/* /usr/bin/  
```

not sure how I can help fix this at the moment.

**Comment by marquiz** [comment]
@Links2004 unfortunately this seems to be a common problem, particularly on armv7 🙁
https://github.com/docker/buildx/issues/350

Somehow related to network setup, location or smth else as on my home desktop the armv7 build succeeded but it fails everywhere else.

**Pull request merged**
