### PR TITLE
go.mod: update github.com/klauspost/cpuid to v2.1.0

### PR DESCRIPTION
**Pull request by mythi**
Fixes: #844

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
Back-to-the-office. Sorry about the delay 🙄

Looks basically good. I was just wondering do we want to advertise some of the new features in the [cpuid list in the docs](https://kubernetes-sigs.github.io/node-feature-discovery/master/get-started/features.html#x86-cpuid-flags-partial-list)?

/ok-to-test

**Comment by ionutnechita** [comment]
Any updates here?

**Comment by marquiz** [comment]
> Any updates here?

I just had this one question about documentation. Any thoughts on that?

/retest

**Comment by mythi** [comment]
> > Any updates here?
> 
> I just had this one question about documentation. Any thoughts on that?

I can add those. Looks like this release added some SVM bits too but perhaps documenting those can be covered separately part of #832

**Comment by marquiz** [comment]
> I can add those

Cool, thanks. Not necessarily adding everything but only those that look likely to be useful to end users 😄

**Comment by mythi** [comment]
Added `AVXVNNI` to docs (that was the only one that fit)

**Review by marquiz — APPROVED** [review]
Thanks @mythi! 

/lgtm

**Pull request merged**
