### PR TITLE
Detect CPU Model

### PR DESCRIPTION
**Pull request by AshwiniGhanwat**
Changes made in the following files:

- deployment/components/common/worker-mounts-combined.yaml
- deployment/components/common/worker-mounts.yaml
- deployment/helm/node-feature-discovery/templates/worker.yaml
- source/config.go
- source/cpu/cpu.go
-  test/e2e/e2e-test-config.example.yaml
- test/e2e/node_feature_discovery.go

Included all comments for PR https://github.com/kubernetes-sigs/node-feature-discovery/pull/621

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
I think we could get all this information using `github.com/klauspost/cpuid` that we already depend on. No need to mount or parse proc/cpuinfo.

One bureaucratical note: when addressing comments please update this PR instead of closing it and opening a new one. We wan't to have all history (code, conversation, comments etc...) under one PR and also not clutter Github with numerous PRs about the same subject.

/ok-to-test

**Comment by marquiz** [comment]
@AshwiniGhanwat could you also tidy up the commit message a bit. At least drop `#270` from the subject line. Also, in the commit message body you could describe in more detail what new features are actually detected

/retitle Detect CPU Model

**Comment by ArangoGutierrez** [comment]
Hey @AshwiniGhanwat , any updates on this effort?

**Comment by ArangoGutierrez** [comment]
> I think we could get all this information using `github.com/klauspost/cpuid` that we already depend on. No need to mount or parse proc/cpuinfo.
> 
> One bureaucratical note: when addressing comments please update this PR instead of closing it and opening a new one. We wan't to have all history (code, conversation, comments etc...) under one PR and also not clutter Github with numerous PRs about the same subject.
> 
> /ok-to-test

Implementation with `klauspost` -> https://github.com/kubernetes-sigs/node-feature-discovery/pull/792

**Comment by marquiz** [comment]
Superseded/implemented by #792 
/close

**Pull request closed without merging**
