### PR TITLE
chore: update tolerations and affinities to control-plane

### PR DESCRIPTION
**Pull request by morremeyer**
This updates the tolerations and affinities to also respect the term „control-plane“ which will eventually replace „master“

### CODE REVIEW

**Comment by marquiz** [comment]
Thanks @morremeyer for the patch!

Please update the relevant yaml templates, too (`nfd-master.yaml.template`, `nfd-daemonset-combined.yaml.template`)

/ok-to-test

**Comment by morremeyer** [comment]
@marquiz I updated the `nfd-master.yaml.template`. As the daemonset has neither tolerations nor affinities, I didn’t change anything there.

**Comment by marquiz** [comment]
> @marquiz I updated the `nfd-master.yaml.template`. As the daemonset has neither tolerations nor affinities, I didn’t change anything there.

Thanks @morremeyer . Could you update `nfd-prune.yaml.template` too. Then we can merge this

**Comment by morremeyer** [comment]
Thanks and done!

**Review by marquiz — APPROVED** [review]
Thanks for the patch @morremeyer! Looks good now 👍 
/lgtm

**Pull request merged**
