### PR TITLE
Add missing TopologyManagerPolicy

### PR DESCRIPTION
**Pull request by PiotrProkop**
Version `0.0.13` of NodeResourceTopology API added missing `TopologyManagerPolicy` for other policies than `single-numa-node`. This PR adds support for those new values.

### CODE REVIEW

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
Hi @PiotrProkop thanks for the PR, could you add a small description to the PR/Commit, thanks!

**Comment by PiotrProkop** [comment]
@ArangoGutierrez yeah, of course!

**Review by marquiz — APPROVED** [review]
Thanks @PiotrProkop, looks good to me 👍

**Pull request merged**
