### PR TITLE
scripts/test-infra: provide PR info to codecov

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
Looks like it worked as expected
/unhold

**Comment by marquiz** [comment]
Hmm, codecov is still not able to report back
/hold

**Comment by marquiz** [comment]
/retitle scripts/test-infra: provide PR info to codecov

**Comment by marquiz** [comment]
Another try, added '-P` to denote the PR number

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
