### PR TITLE
Fixed the incorrect references 

### PR DESCRIPTION
**Pull request by vaibhav2107**
The PR fixes some references that present in the [customization guide](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/advanced/customization-guide.html) in Advanced Section

### CODE REVIEW

**Comment by vaibhav2107** [comment]
Hi @ArangoGutierrez , @zvonkok 
Could you please have a look.

**Review by ArangoGutierrez — COMMENTED** [review]
PR lgtm
/cc @marquiz 
/lgtm

**Comment by ArangoGutierrez** [comment]
> @vaibhav2107: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-node-feature-discovery-verify-docs	[afd5bc4](https://github.com/kubernetes-sigs/node-feature-discovery/commit/afd5bc4d811d831bc893208804bbdc8c0eaa453d)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_node-feature-discovery/769/pull-node-feature-discovery-verify-docs/1491065368813244416)	true	`/test pull-node-feature-discovery-verify-docs`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=node-feature-discovery&pr=769). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Avaibhav2107). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/node-feature-discovery/issues?q=is:issue+is:open) when you hit one in your PR.

@vaibhav2107 please fix

**Review by marquiz — COMMENTED** [review]
Thanks @vaibhav2107, looks good. You just need to fix the line length, i.e. wrap the lines you modified to correct lenght in order to make mdlint happy

**Comment by vaibhav2107** [comment]
Thanks @marquiz , @ArangoGutierrez for reviewing,
will fix it.

**Comment by ArangoGutierrez** [comment]
Any updates here @vaibhav2107 ?

**Comment by vaibhav2107** [comment]
PTAL @ArangoGutierrez , @marquiz

**Comment by marquiz** [comment]
> PTAL @ArangoGutierrez , @marquiz

Umm, the lines are not quite wrapped right and mdlint is unhappy
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_node-feature-discovery/769/pull-node-feature-discovery-verify-docs/1495674448898953216

Please fix these and also squash the PR into one commit

**Comment by marquiz** [comment]
ping @vaibhav2107 please update the pr

**Review by marquiz — APPROVED** [review]
👍

**Comment by vaibhav2107** [comment]
Ah, at last, cleared all tests,

**Comment by vaibhav2107** [comment]
Thanks @marquiz for approving, could you help in squashing the commits as got some issue in my local

**Pull request merged**
