### PR TITLE
not need close

### PR DESCRIPTION
**Pull request by goushicui**

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Hey @goushicui thanks for the patch, could you check the CLA info first, and second, please add more info to both the PR header and the commit. a 2 or 3 liner explanation on why this is needed, thanks again!

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
Please amend the commit with some verbose explanation on why this is needed

/hold

**Comment by ArangoGutierrez** [comment]
the assignee is meant to carry the patch process and reviews, is not the same PR Author
/unassign goushicui

**Comment by goushicui** [comment]
close or not close the chan may not affect WaitForReady func, i think it is not necessary

**Comment by marquiz** [comment]
> close or not close the chan may not affect WaitForReady func, i think it is not necessary

It is necessary and deliberate. The ready signal is emitted only once. Without closing the channel further calls `WaitForReady()` would fail with a timeout (as it would wait for the signal that won't be emitted). Suggesting to close this PR

**Pull request closed without merging**
