### PR TITLE
scripts: move hacky scripts to hack directory

### PR DESCRIPTION
**Pull request by marquiz**
Move prepare-release.sh and kustomize.sh from scripts/ to hack/.

### CODE REVIEW

**Review by fmuyassarov — APPROVED** [review]
This makes sense and it is scripts dir is cleaner now. 
/lgtm

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by marquiz** [comment]
Rebased

**Comment by marquiz** [comment]
ping @ArangoGutierrez @zvonkok

**Pull request merged**
