### PR TITLE
don't merge, this is for verification

### PR DESCRIPTION
**Pull request by fmuyassarov**

### CODE REVIEW

**Comment by marquiz** [comment]
@fmuyassarov looks like we would close this one

**Comment by fmuyassarov** [comment]
> @fmuyassarov looks like we would close this one

I still would like to keep until I make the codecov to be able to report here on the pull request.

**Comment by marquiz** [comment]
> I still would like to keep until I make the codecov to be able to report here on the pull request.

Ach, yes:
```console
[2023-04-25T20:13:22.484Z] ['error'] There was an error running the uploader: 
Unable to detect SHA and slug, please specify them manually.
See the help for more details.
```

**Comment by fmuyassarov** [comment]
We have done the tests and no longer need this. As such, closing it.
/close

**Pull request closed without merging**
