### PR TITLE
[release-0.14] Update references to release v0.14.5

### PR DESCRIPTION
**Pull request by marquiz**
Manually generated with:

    ./hack/prepare-release.sh -g 1.20.14 v0.14.5

### CODE REVIEW

**Comment by marquiz** [comment]
Let's wait for feedback in #1614 
/hold

**Comment by marquiz** [comment]
Looks like good to go (https://github.com/kubernetes-sigs/node-feature-discovery/issues/1614#issuecomment-1999244597)
/unhold

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
