### PR TITLE
release 0.8: cherry-picks from master

### PR DESCRIPTION
**Pull request by marquiz**
- github: update gh-pages on published releases – will streamline release process in case we need v0.8.x point releases
- docs: describe Helm repo as the primary option for Helm
- docs: Add Table header to master/worker chart parameters
- helm: fix nfd worker tolerations value

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
LGTM
leaving it to @adrianchiris for the Helm bits

**Comment by marquiz** [comment]
Added one more helm fix

**Pull request merged**
