### PR TITLE
nfd-topology-updater: Add liveness probe

### LINKED ISSUE #1550: Liveness probe for nfd-topology-updater
**What would you like to be added**:

Add a liveness and/or readiness probe, e.g. a gRPC health server, to nfd-topology-updater.

**Why is this needed**:

More eyes on the well-being of nfd-topology-updater instances.

### PR DESCRIPTION
**Pull request by ozhuraki**
Closes #1550

### CODE REVIEW

**Comment by marquiz** [comment]
Thanks @ozhuraki 
/assign @PiotrProkop 
/ok-to-test

**Comment by marquiz** [comment]
@ozhuraki please rebase

**Comment by ozhuraki** [comment]
@marquiz 
Rebased, please take a look

**Review by marquiz — APPROVED** [review]
Thanks @ozhuraki 👍

@PiotrProkop PTAL

**Comment by PiotrProkop** [comment]
Looks good. Thanks @ozhuraki 
/lgtm

**Pull request merged**
