### PR TITLE
nfd-master: add config file options for logging

### LINKED ISSUE #1206: nfd-master: logging parameters in config file
**What would you like to be added**:

Make klog parameters part of the (dynamic) configuration file, similarly to what we have for [nfd-worker](https://kubernetes-sigs.github.io/node-feature-discovery/v0.13/reference/worker-configuration-reference.html#coreklog).

This feature would make it possible to change logging parameters without re-starting nfd-master daemon.

Config file example

```yaml
klog:
  v: "4"
```

**Why is this needed**:

Better usability, dynamic run-time configuration of logging.

### PR DESCRIPTION
**Pull request by AhmedGrati**
Resolves #1206.

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
I like it! 
but makes me think, since now master and worker have the same functions on `cmd/nfd-*` should we have this `klog` flag parsing fuctions in a shared location? `pkg/utils/klog`?

**Comment by ArangoGutierrez** [comment]
Do we want this in v0.14?

**Comment by marquiz** [comment]
> Do we want this in v0.14?

I think this is a very low-risk addition that would be nice to have. Same functionality is already present in nfd-worker. I quickly verified this last night ✅

**Comment by marquiz** [comment]
> but makes me think, since now master and worker have the same functions on `cmd/nfd-*` should we have this `klog` flag parsing fuctions in a shared location? `pkg/utils/klog`?

Good point. I think this could be future refactoring/enhancement. We could create an issue about this. WDYT?

**Pull request merged**
