### PR TITLE
Update go version in Dockerfile

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Update go version in Docker build image to v1.13.5

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by marquiz** [comment]
Thank you for the patch. I think we should keep travis.yml in sync with the Dockerfile so that would need to be updated, too.

**Comment by ArangoGutierrez** [comment]
sure, will patch the `.travis.yml` file as well

**Comment by ArangoGutierrez** [comment]
@marquiz  you think we should do 
```yaml
language: go
go:
  - "1.13"
  - "1.13.x"
```
or just 1.13?

**Comment by marquiz** [comment]
I think one version should be enough. We could stay in full sync with the dockerfile and use `1.13.5`(?)

**Comment by ArangoGutierrez** [comment]
done

**Comment by marquiz** [comment]
Hmm, end-to-end tests fail with go 1.13 🤔 

Looks like the kubernetes version we're using as a dep (the e2e test framework from it) is incompatible with go 1.13. We should update the dep(s) to k8s v1.17 and try with that.

**Comment by marquiz** [comment]
Updating the deps wasn't quite that simple. I just submitted #282 to do that. We should merge that first and then try your PR on top of it.

**Comment by ArangoGutierrez** [comment]
thanks for #282 , rebased and updated

**Pull request merged**
