### PR TITLE
helm: add priorityClassName option

### PR DESCRIPTION
**Pull request by ArangoGutierrez**

### CODE REVIEW

**Comment by AhmedThresh** [comment]
@ArangoGutierrez Wouldn't be useful if we add the same config for Kustomize also?

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez Wouldn't be useful if we add the same config for Kustomize also?

the thing is, in kustomize we don't have a clear way of passing input as with helm values file. I prefer to keep kustomize as is for now

**Review by marquiz — COMMENTED** [review]
Thanks @ArangoGutierrez. Makes sense

I think we should use the same priority class for nfd-gc and nfd-topology-updater, too(?)

Suggestion regarding the commit message: You could prefix the title with the "helm:" context as with the PR title
/retitle helm: add priorityClassName option

**Comment by ArangoGutierrez** [comment]
@marquiz can we add this to v0.16?

**Review by marquiz — APPROVED** [review]
Looks good to me

**Comment by marquiz** [comment]
> can we add this to v0.16?

Yeah, sure it will be there, once lgtm'd 😄

**Review by AhmedThresh — APPROVED** [review]

**Pull request merged**
