### PR TITLE
topology-gc: simplify listing of node objects

### PR DESCRIPTION
**Pull request by marquiz**
Hopefully makes the code slightly more readable.

### CODE REVIEW

**Comment by marquiz** [comment]
#1310 merged
/unhold

**Comment by PiotrProkop** [comment]
Makes sense to use node name instead of `cache.MetaNamespaceKeyFunc(object)`, since node is not namespaced object.

**Comment by marquiz** [comment]
> Makes sense to use node name instead of `cache.MetaNamespaceKeyFunc(object)`, since node is not namespaced object.

So what's your verdict on the PR? 😇

**Comment by marquiz** [comment]
dockerhub pull rate limit 🤯

**Comment by instructorUz** [comment]
> dockerhub pull rate limit 🤯

shall we apply for https://www.docker.com/community/open-source/application/ , https://github.com/cncf/servicedesk#my-project-is-affected-by-the-docker-hub-rate-limits-policy-changes-what-can-i-do?

**Comment by marquiz** [comment]
> Should we perhaps apply for the https://github.com/cncf/servicedesk#my-project-is-affected-by-the-docker-hub-rate-limits-policy-changes-what-can-i-do ?

Thx for the pointer, I wasn't aware of that 👍 I'll send an application...

**Pull request merged**
