### PR TITLE
source/cpu: fix build flags of cpuid detection

### PR DESCRIPTION
**Pull request by marquiz**
Non-x86_64 platforms are virtually only buildable on Linux because the getauxval() glibc function is missing on many platforms.

### CODE REVIEW

**Comment by marquiz** [comment]
Quick Friday night hack. Need to verify/think twice this doesn't break anything
/hold

**Comment by marquiz** [comment]
Works for x86_64 (linux and darwin) and arm64 darwin
/unhold
/assign @ArangoGutierrez @zvonkok

**Comment by marquiz** [comment]
ping @yselkowitz @lubinszARM

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
