### PR TITLE
test: add code coverage reporting

### PR DESCRIPTION
**Pull request by fmuyassarov**
Add code coverage reporting so that the report is then available to the PR author and reviewers via codecov GitHub app.

@marquiz for uploading/reporting the coverage results, we need to run `make test`. We already run the `make test` with one of the Prow job and I didn't want to add another one in the form of GitHub action. But GA is the most straightforward way of adding codecov and uploading it. There is an uploader available which can be executed from shell as well, so that can be added into Prow job run section, but for that codecov requires the token. We could store the token as a secret on GitHub but I don't know if there is a way actually for the Prow to ready/fetch that token. At least I have not seen anything like that. 

With GitHub actions it is not a problem, because we just pass the `${{ secrets.CODECOV_TOKEN }}` and voilà.

Do you have any other alternatives in mind or if not shall I go for adding another make test as GitHub action? I also thought that maybe we drop running unit tests from Prow to avoid duplication but Prow runs on much faster environment than what GitHub provides for free.

Fixes: https://github.com/kubernetes-sigs/node-feature-discovery/issues/1033

### CODE REVIEW

**Comment by fmuyassarov** [comment]
@marquiz  Actually from https://github.com/kubernetes-sigs/node-feature-discovery/issues/1033, I see that you have already mentioned that we can add codecov token as a secret in the k8s test-infra cluster. Do you know what's the procedure for that?

**Review by marquiz — APPROVED** [review]
Thanks @fmuyassarov for working on this.

I think integrating it into prow/test-infra (instead of Github actions) would be the way to go, as you pondered

**Comment by fmuyassarov** [comment]
/cc @ArangoGutierrez

Just general update: we need to add a secret into the test infra k8s cluster and I'm in progress of reaching out the team responsible for that. Once done, I will submit another patch in the test-infra to add covecov report uploading steps.

**Comment by marquiz** [comment]
> Just general update: we need to add a secret into the test infra k8s cluster and I'm in progress of reaching out the team responsible for that. Once done, I will submit another patch in the test-infra to add codecov report uploading steps.

But this PR is not dependent on that

**Comment by fmuyassarov** [comment]
> > Just general update: we need to add a secret into the test infra k8s cluster and I'm in progress of reaching out the team responsible for that. Once done, I will submit another patch in the test-infra to add codecov report uploading steps.
> 
> But this PR is not dependent on that

yes yes. It was just a heads up for Eduardo, because we discussed with you the plan in slack but not here.

**Comment by ArangoGutierrez** [comment]
> > > Just general update: we need to add a secret into the test infra k8s cluster and I'm in progress of reaching out the team responsible for that. Once done, I will submit another patch in the test-infra to add codecov report uploading steps.
> > 
> > 
> > But this PR is not dependent on that
> 
> yes yes. It was just a heads up for Eduardo, because we discussed with you the plan in slack but not here.

So... Can I lgtm?  or wait?

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
