### PR TITLE
Fix prepare-release to work on MacOs-arm64

### PR DESCRIPTION
**Pull request by ArangoGutierrez**

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
/retile Fix prepare-release to work on MacOs-arm64

**Comment by ArangoGutierrez** [comment]
/retile Fix prepare-release to work on MacOs-arm64

**Comment by ArangoGutierrez** [comment]
/retitle Fix prepare-release to work on MacOs-arm64

**Review by marquiz — CHANGES_REQUESTED** [review]
This breaks usage on Linux so NACK. I don't know if there's a cross-compatible format for `-i` between the Linux and BSD variants of sed 🧐

**Comment by ArangoGutierrez** [comment]
> This breaks usage on Linux so NACK. I don't know if there's a cross-compatible format for `-i` between the Linux and BSD variants of sed 🧐

/close

**Comment by marquiz** [comment]
I you want to invest in this, you could of course (try to) detect which variant of sed (Linux vs BSD) is installed and parameterize the handling of `-i` depending on that...

**Pull request closed without merging**
