### PR TITLE
release-0.9: update references to v0.9.0

### PR DESCRIPTION
**Pull request by marquiz**
Generated with:

scripts/prepare-release.sh v0.9.0 markus.lehtonen@intel.com

### CODE REVIEW

**Comment by marquiz** [comment]
I want to still double-check this myself, too 😺 
/hold

**Review by ArangoGutierrez — APPROVED** [review]
testing before lgtm

**Comment by marquiz** [comment]
I think I'm happy with this
/unhold

**Review by ArangoGutierrez — APPROVED** [review]
Let there be a v0.9.0 release!! 
/lgtm

**Pull request merged**
