### PR TITLE
nfd-master: always start gRPC server

### LINKED ISSUE #1032: gRPC Health probe fails when running  with -enable-nodefeature-api
When running NFD with `-enable-nodefeature-api`, the gRPC health probe fails 

```bash
Events:
  Type     Reason     Age                       From     Message
  ----     ------     ----                      ----     -------
  Warning  Unhealthy  21m (x5110 over 2d23h)    kubelet  Readiness probe failed: command "/usr/bin/grpc_health_probe -addr=:8080" timed out
  Warning  BackOff    6m9s (x16447 over 2d23h)  kubelet  Back-off restarting failed container
  Warning  Unhealthy  69s (x4053 over 2d23h)    kubelet  Liveness probe failed: command "/usr/bin/grpc_health_probe -addr=:8080" timed out
[2:49](https://kubernetes.slack.com/archives/DTRREAN6A/p1673617787536269)

[eduardo@fedora aws-kube-ci]$ kubectl --kubeconfig kubeconfig get pods -n node-feature-discovery 
NAME                          READY   STATUS             RESTARTS           AGE
gpu-feature-discovery-pnt92   1/1     Running            0                  2d23h
nfd-master-668b74498d-kj5fm   0/1     CrashLoopBackOff   1350 (2m58s ago)   2d23h
nfd-master-cd7f6d78d-gg44s    0/1     CrashLoopBackOff   1355 (108s ago)    2d23h
nfd-worker-sgbgj              1/1     Running            0                  2d23h
[2:50](https://kubernetes.slack.com/archives/DTRREAN6A/p1673617806643339)
```
Master pod is crashing due to  grpc helath probe failure

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Fixes #1032

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
Thanks for PR @ArangoGutierrez  I think this is a nice and small fixup for now. Later on, when/if dropping gRPC we probably want to do something else (`sigs.k8s.io/controller-runtime/pkg/healthz` or smth).

One small ask: could you open up a bit in the commit message what and why is done, i.e. start gRPC server but don't register the labeler service because we want to enable grpc health probe but don't wan't the labeling API to be enabled.

**Review by marquiz — APPROVED** [review]
Looks good to me now!
/retitle nfd-master: always start gRPC server

**Review by fmuyassarov — COMMENTED** [review]
/lgtm
Thanks @ArangoGutierrez

**Pull request merged**
