### PR TITLE
feature-gates: mark NodeFeatureAPI as GA

### PR DESCRIPTION
**Pull request by marquiz**
The feature gate is locked to true. That is, it is not possible to revert back to the gPRC-based communication which makes the gRPC API ready for removal.

### CODE REVIEW

**Comment by marquiz** [comment]
Refs #1546, let's wait a bit for comments there

/hold

**Comment by marquiz** [comment]
Rebased, more updates on the documentation. There are still some tidbits left in the docs but I was planning to address them separately (Helm, TLS, developer guide) to make reviews easier (i.e. avoid this becoming a mega-PR here). My general thinking that it makes for an easier (and a better) review I we do this in smaller pieces like now listed #1546.

**Comment by marquiz** [comment]
Rebased. No objections so far :) 
/unhold

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
