### PR TITLE
source/network: run discovery under /host-sys

### PR DESCRIPTION
**Pull request by marquiz**
The default deployment mounts /sys from the host under /host-sys so
let's use that. No need to use hostNetwork after that so drop it from
the worker deployment templates.

### CODE REVIEW

**Comment by Ethyling** [comment]
We are looping over the host interfaces using `netInterfaces, err := net.Interfaces()`. Without `hostNetwork` the interfaces are the one from the container. I think we should loop over interfaces using the sysfs instead?

**Comment by marquiz** [comment]
> We are looping over the host interfaces using `netInterfaces, err := net.Interfaces()`. Without `hostNetwork` the interfaces are the one from the container. I think we should loop over interfaces using the sysfs instead?

Yes, I realized this when I was writing the sysfs patch in #318, but didn't have the time to fix this one (should've put the hold label here 😬 ). I now pushed a new version ditching "net" for good and doing all discovery under host sysfs. I haven't tested this properly yet, though.

**Comment by Ethyling** [comment]
LGTM

But golangci-lint is not happy:
```golangci-lint run --timeout 5m0s
source/network/network.go:33:2: `flagBroadcast` is unused (deadcode)
        flagBroadcast
        ^
source/network/network.go:34:2: `flagDebug` is unused (deadcode)
        flagDebug
        ^
```

**Comment by marquiz** [comment]
> But golangci-lint is not happy:

Should've checked that myself as I was the one who mandated that rule. Fixed, now.

**Pull request merged**
