### PR TITLE
cpu: re-organize security features

### PR DESCRIPTION
**Pull request by marquiz**
Move existing security/trusted-execution related features (i.e. SGX and
SE) under the same `security` feature, deprecating the old features. The
motivation for the change is to keep the source code and user interface
more organized as we experience a constant inflow of similar security
related features. This change will affect the user interface so it is
less painful to do it early on.

New feature labels will be:

```
  feature.node.kubernetes.io/cpu-security.se.enabled
  feature.node.kubernetes.io/cpu-security.sgx.enabled
```

and correspondingly new  **`cpu.security`** feature with `se.enabled` and
`sgx.enabled` elements will be available for custom rules, for example:

```
      - name: "sample sgx rule"
        labels:
          sgx.sample.feature: "true"
        matchFeatures:
          - feature: cpu.security
            matchExpressions:
              "sgx.enabled": {op: IsTrue}
```

At the same time deprecate old labels `cpu-sgx.enabled` and
`cpu-se.enabled` feature labels and the corresponding features for
custom rules. These will be removed in the future causing an effective
change in NFDs user interface.

### CODE REVIEW

**Comment by marquiz** [comment]
RFC
/hold

**Comment by zvonkok** [comment]
@marquiz Where are we with the topic of having shorter feature labels? I think this is also still open. I think we should start thinking of doing that as well as soon as possible before we are adding features that are used by other projects and it creates to much confusion when switching.

**Comment by marquiz** [comment]
Any thoughts on this? @mythi @zvonkok @ArangoGutierrez ?

**Comment by marquiz** [comment]
> I added my thoughts in [#832 (comment)](https://github.com/kubernetes-sigs/node-feature-discovery/issues/832#issuecomment-1191202692) earlier

Ach yes, sorry I already forgot that comment 😊 Suggestions (or PRs) how to change the feature descriptions in docs are welcome.

Removing the RFC status of this PR
/unhold

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
