### PR TITLE
Add Netlify configuration file

### PR DESCRIPTION
**Pull request by fmuyassarov**
This patch adds netlify configuration file which includes steps needed to build
the documentation as part of presubmit review process. I was planning to add
these commands from the web UI, but it is better to keep it here transparency
and the version control purposes.

Prerequisite for https://github.com/kubernetes-sigs/node-feature-discovery/issues/886 and https://github.com/kubernetes/org/issues/3665

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
Thanks @fmuyassarov! Looks simple enough to me. Haven't verified this myself but I trust you 😊

**Comment by fmuyassarov** [comment]
> Thanks @fmuyassarov! Looks simple enough to me. Haven't verified this myself but I trust you blush

Thanks, actually I forgot to mention that I have done prior test based on the config and example of deployed build is available here: https://632439999eada305e60df2e4--cozy-malabi-ecd098.netlify.app/get-started/index.html

**Pull request merged**
