### PR TITLE
codegen: fix code-generation

### PR DESCRIPTION
**Pull request by fmuyassarov**
Our make-generate is currently broken as shown below and this PR fixes it by bumping mockery version and disabling buildvcs to avoid go VCS status error. More info on commit messages. Last [commit](https://github.com/kubernetes-sigs/node-feature-discovery/commit/80a38ac6c9cdb66578fa02138adbd4e681901818) is about re-running make generate (auto-generated code).

NOTE: mockery latest version is 2.22.1 but that requires mockery.yaml file to be available. I'm not sure if we really need it. But if yes, we can do it separately because this PR is about fixing the code generation. 

```shell
$ make generate 
docker build \
    --build-arg BUILDER_IMAGE=golang:1.20-bullseye \
    -t nfd-generator \
    -f Dockerfile_generator .
[+] Building 1.0s (10/10) FINISHED                                                                                                                                                                 
 => [internal] load .dockerignore                                                                                                                                                             0.0s
 => => transferring context: 156B                                                                                                                                                             0.0s
 => [internal] load build definition from Dockerfile_generator                                                                                                                                0.0s
 => => transferring dockerfile: 990B                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/golang:1.20-bullseye                                                                                                                       1.0s
 => [auth] library/golang:pull token for registry-1.docker.io                                                                                                                                 0.0s
 => [1/5] FROM docker.io/library/golang:1.20-bullseye@sha256:51ff22f03320894402290ba7dfd83ee05b61e58b5381d76b40f2e3a370d81da3                                                                 0.0s
 => CACHED [2/5] RUN go install github.com/vektra/mockery/v2@v2.13.0 &&     go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2 &&     git clone https://github.com/kubernetes  0.0s
 => CACHED [3/5] RUN apt-get update && apt-get install unzip                                                                                                                                  0.0s
 => CACHED [4/5] RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-x86_64.zip &&     unzip protoc-3.17.3-linux-x86_64.zip -d /usr/local  0.0s
 => CACHED [5/5] WORKDIR /go/node-feature-discovery                                                                                                                                           0.0s
 => exporting to image                                                                                                                                                                        0.0s
 => => exporting layers                                                                                                                                                                       0.0s
 => => writing image sha256:9ea9bf4bad6e19752c6d8987549a9fe797138918661312bb1b5aa49df2a9ee39                                                                                                  0.0s
 => => naming to docker.io/library/nfd-generator                                                                                                                                              0.0s
docker run --rm \
    -v "`pwd`:/go/node-feature-discovery" \
    -v "`go env GOCACHE`:/.cache" \
    -v "`go env GOMODCACHE`:/go/pkg/mod" \
    --user=`id -u`:`id -g`\
    nfd-generator \
    ./hack/generate.sh
10 Mar 23 22:05 UTC INF Starting mockery dry-run=false version=v2.13.0
10 Mar 23 22:05 UTC INF Walking dry-run=false version=v2.13.0
2023/03/10 22:05:40 internal error: package "github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/generated/clientset/versioned" without types was imported from "sigs.k8s.io/node-feature-discovery/pkg/apihelper"
pkg/apihelper/apihelpers.go:19: running "mockery": exit status 1
+ go-to-protobuf --output-base=. --go-header-file ../../../../hack/boilerplate.go.txt --proto-import ../../../../vendor/ --packages +sigs.k8s.io/node-feature-discovery/pkg/apis/nfd/v1alpha1=v1alpha1 --keep-gogoproto=false --apimachinery-packages -k8s.io/apimachinery/pkg/util/intstr
topological order bytes
topological order encoding/json
topological order errors
topological order fmt
topological order github.com/gogo/protobuf/proto
topological order github.com/gogo/protobuf/sortkeys
topological order github.com/google/gofuzz
topological order io
topological order k8s.io/api/core/v1
topological order k8s.io/apimachinery/pkg/apis/meta/v1
topological order k8s.io/apimachinery/pkg/runtime
topological order k8s.io/apimachinery/pkg/runtime/schema
topological order k8s.io/klog/v2
topological order math
topological order math/bits
topological order reflect
topological order regexp
topological order runtime/debug
topological order sigs.k8s.io/node-feature-discovery/pkg/utils
topological order sort
topological order strconv
topological order strings
topological order text/template
topological order k8s.io/apimachinery/pkg/util/intstr
topological order sigs.k8s.io/node-feature-discovery/pkg/apis/nfd/v1alpha1
+ mv sigs.k8s.io/node-feature-discovery/pkg/apis/nfd/v1alpha1/generated.pb.go sigs.k8s.io/node-feature-discovery/pkg/apis/nfd/v1alpha1/generated.proto .
+ rm -rf sigs.k8s.io
10 Mar 23 22:05 UTC INF Starting mockery dry-run=false version=v2.13.0
10 Mar 23 22:05 UTC INF Walking dry-run=false version=v2.13.0
2023/03/10 22:05:42 internal error: package "context" without types was imported from "sigs.k8s.io/node-feature-discovery/pkg/labeler"
pkg/labeler/doc.go:20: running "mockery": exit status 1
10 Mar 23 22:05 UTC INF Starting mockery dry-run=false version=v2.13.0
10 Mar 23 22:05 UTC INF Walking dry-run=false version=v2.13.0
2023/03/10 22:05:42 internal error: package "github.com/stretchr/testify/mock" without types was imported from "sigs.k8s.io/node-feature-discovery/source"
source/source.go:19: running "mockery": exit status 1
make: *** [Makefile:145: generate] Error 1
```

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
Thanks @fmuyassarov for the fix!

One question: which part of the auto-generation fails with the `error obtaining VCS status`?

Also, maybe you could put all autogenerated changes in the last commit (removing auto-generated parts from the first commit)?

**Comment by fmuyassarov** [comment]
> One question: which part of the auto-generation fails with the `error obtaining VCS status`?

when running generate-groups.sh. https://github.com/kubernetes-sigs/node-feature-discovery/blob/adea670ded0330a5534b72e2a6ab167aff6b2e6f/hack/generate.sh#L20


> Also, maybe you could put all autogenerated changes in the last commit (removing auto-generated parts from the first commit)?

Yep, I myself didn't notice actually those committed (used `git add .`) changes. But it if fixed now, thanks for the suggestion.

**Review by marquiz — APPROVED** [review]
Thanks for the update

I haven't seen the VCS status problem but it possibly occurred if you run the generation under a git worktree(?) But better to fix that problem in any case.

/assign @ArangoGutierrez

**Comment by fmuyassarov** [comment]
> I haven't seen the VCS status problem but it possibly occurred if you run the generation under a git worktree(?) But better to fix that problem in any case.
> 
If you checkout to https://github.com/kubernetes-sigs/node-feature-discovery/pull/1083/commits/a58cc0a53bc6ca0c09836d1242b080f265d92a1f, which doesn't include `-buildvcs=false`, and run make generate you will most probably see the same. But I guess it is as you said that it happens when running under a git worktree.

**Pull request merged**
