### PR TITLE
Update the link of slack channel

### PR DESCRIPTION
**Pull request by vaibhav2107**
Ref: #658

### CODE REVIEW

**Comment by vaibhav2107** [comment]
Hi @adrianchiris , @ArangoGutierrez 
Could you please have a look

**Review by adrianchiris — APPROVED** [review]

**Review by marquiz — APPROVED** [review]
Thanks @vaibhav2107

**Comment by vaibhav2107** [comment]
Thanks @adrianchiris , @marquiz for approving.

**Pull request merged**
