### PR TITLE
WIP: Topology updater: TM policy from configz endpoint

### PR DESCRIPTION
**Pull request by Tal-or**
Build on top of #525 and #528

This patch allows nfd-master to pull the config from the Kubernetes configz endpoint.
This update introduces --obtain-kubelet-config=\<option\> as it provides the option to obtain Kubelet config from configz-endpoint in addition to the already existing way of obtaining kubelet-config-file.

Design Document: [here](https://docs.google.com/document/d/1Q-4wSu1tzmbOXyGk_2r5_mK6JdXXJA-bOd3cAtBFnwo/edit?ts=5f24171f#)
Issue: #333
Documentation: #526

### CODE REVIEW

**Comment by Tal-or** [comment]
Added CLA

**Comment by Tal-or** [comment]
signed

**Comment by Tal-or** [comment]
I signed it

**Comment by Tal-or** [comment]
I signed it

**Review by marquiz — COMMENTED** [review]
Hmm, I'm not sure about this one 🧐  Is the configz endpoint something that is meant for production use? Also, I'd like to limit the access to the kubernetes api

**Review by marquiz — CHANGES_REQUESTED** [review]
Please rebase

/ok-to-test

**Comment by catblade** [comment]
@Tal-or  is this one abandoned?

**Comment by Tal-or** [comment]
Closing this PR for now, due to what mentioned [here](https://github.com/kubernetes-sigs/node-feature-discovery/pull/530#pullrequestreview-737209082) and time constraints.

I Will issue a new PR in the future if there will be a justification for that.

**Pull request closed without merging**
