### PR TITLE
GO Update version to 1.20

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
This patch
- Bumps GO to 1.20
- Updates deps by running "go mod tidy"

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
Thanks @ArangoGutierrez, let's keep up with the latest and greatest

**Comment by marquiz** [comment]
@ArangoGutierrez, could you also submit a PR against https://github.com/kubernetes/test-infra to update the presubmit and  postsubmit jobs for the master branch to use v1.20
/hold

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez, could you also submit a PR against https://github.com/kubernetes/test-infra to update the presubmit and postsubmit jobs for the master branch to use v1.20 /hold

You are right, will do after lunch

**Comment by ArangoGutierrez** [comment]
@marquiz -> https://github.com/kubernetes/test-infra/pull/28770

**Comment by marquiz** [comment]
@ArangoGutierrez we might need #1061

**Pull request merged**
