### PR TITLE
scripts/test-infra: drop the unused build-image script

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
Pending https://github.com/kubernetes/test-infra/pull/32916
/hold

/assign @ArangoGutierrez

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Review by TessaIO — APPROVED** [review]

**Comment by marquiz** [comment]
/unhold

ping @ArangoGutierrez

**Pull request merged**
