### PR TITLE
Bump Go to v1.22

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
Let's sync with https://github.com/kubernetes/test-infra/pull/31913. Merge that first, then unhold this one
/hold
/assign @ArangoGutierrez

**Review by ArangoGutierrez — APPROVED** [review]
unhold at will 
/lgtm

**Comment by marquiz** [comment]
I think we need #1583

**Comment by marquiz** [comment]
ping @ArangoGutierrez

**Pull request merged**
