### PR TITLE
Documentation: Drop NFD gRPC API

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Part of https://github.com/kubernetes-sigs/node-feature-discovery/issues/1546

### CODE REVIEW

**Comment by marquiz** [comment]
@ArangoGutierrez now this one :wink:

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez now this one 😉

Ready to play!

**Review by marquiz — COMMENTED** [review]
Thanks @ArangoGutierrez for working on this :+1: Needs rebase

Other quick notes:
- deployment/kustomize: has some references to cert-manager that needs to be dropped (I think they're stale leftovers from my own changes :grimacing: )
- master cmdline reference:  drop docs for `-crd-controller` and `-featurerules-controller`
- worker cmdline reference: drop documentation for `-server-name-override`

**Comment by ArangoGutierrez** [comment]
@marquiz PTAL

**Comment by marquiz** [comment]
> @marquiz PTAL

`-featurerules-controller` in nfd-master cmdline ref?

Also rebase needed(?)

**Comment by ArangoGutierrez** [comment]
> -featurerules-controller

done

**Comment by ArangoGutierrez** [comment]
AH?

**Pull request closed without merging**
