### PR TITLE
Switch to flags package in command line arg parsing

### PR DESCRIPTION
**Pull request by marquiz**
Time to let the docopt-go go 😄  One motivation for this change is to move to klog-based logging.

### CODE REVIEW

**Comment by marquiz** [comment]
> I'm not sure what would be the nicest way to handle the nfd-worker cmdline to config overrides. This implements one way but I'm not sure this is the best 🤔

I'm a bit more satisfied with this, now

**Comment by marquiz** [comment]
Exploring some yet another implementation
/hold

**Comment by marquiz** [comment]
> Exploring some yet another implementation

Ach, I didn't end up as nice as I hoped.
/unhold

**Comment by ArangoGutierrez** [comment]
Tested on k8's 1.20+
```bash
Ran 2 of 219 Specs in 35.024 seconds                                                                                                                                                          
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 217 Skipped
```
[patch_444.txt](https://github.com/kubernetes-sigs/node-feature-discovery/files/6036471/patch_444.txt)

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
