### PR TITLE
source/fake: implement FeatureSource

### PR DESCRIPTION
**Pull request by marquiz**
Makes it possible to create fake features for custom rules, enabling
testing.

Depends on #605

### CODE REVIEW

**Comment by marquiz** [comment]
/assign @ArangoGutierrez 

Pending on #605 
/hold

**Comment by ArangoGutierrez** [comment]
> /assign @ArangoGutierrez
> 
> Pending on #605 /hold

Rebase? 
/test all

**Comment by ArangoGutierrez** [comment]
@marquiz this is ready IMO unhold?

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by marquiz** [comment]
Rebase. #605 merged

> @marquiz this is ready IMO unhold?

Yes

/unhold

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
