### PR TITLE
source/network: discover speed of virtual network interfaces

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Review by AhmedGrati — APPROVED** [review]
LGTM!

**Comment by jon-rei** [comment]
Hi, is there an update on this PR? We need this feature to be able to use node-feature-discovery in our environment.

**Comment by jon-rei** [comment]
Thanks @marquiz for the merge. I've just tested it in a development environment and it detects the speed of the virtual bond interface and sets an appropriate label. From my perspective it works.

**Comment by marquiz** [comment]
Thanks @jon-rei for the feedback
/cherry-pick release-0.15

**Comment by marquiz** [comment]
ping @jon-rei: [v0.15.1](https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.15.1) with this feature is now out

**Pull request merged**
