### PR TITLE
Document AVXVNNIINT16 cpuid feature

### PR DESCRIPTION
**Pull request by ozhuraki**
Update to klauspost/cpuid to v2.2.7

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
Thanks @ozhuraki for the PR. The commit message (and PR title) should be changed to match the content of the PR. E.g. "Document AVXVNNIINT16 cpuid feature" or smth

/ok-to-test

**Comment by ozhuraki** [comment]
@marquiz 
Thanks, updated.

**Review by ArangoGutierrez — APPROVED** [review]

**Review by marquiz — APPROVED** [review]
/retitle Document AVXVNNIINT16 cpuid feature

**Pull request merged**
