### PR TITLE
Bump Kubernetes to v1.25.3

### PR DESCRIPTION
**Pull request by fmuyassarov**

### CODE REVIEW

**Comment by marquiz** [comment]
Thanks @fmuyassarov. I'd suggest to bump all k8s packages, too, and possible other deps as well. To keep everything in sync

**Comment by fmuyassarov** [comment]
> Thanks @fmuyassarov. I'd suggest to bump all k8s packages, too, and possible other deps as well. To keep everything in sync

done

**Comment by marquiz** [comment]
Sorry, a small nit on the commit message: I'd change it to smth like `Bump Kubernetes to v1.25.3` as k8s is the "main dependency" of ours with which we kind of try to sync other deps with. Ginkgo and gomega (and others) could be mentioned in the commit msg body. WDYT?

**Comment by fmuyassarov** [comment]
should be ready 😊

**Review by marquiz — APPROVED** [review]
Nice work @fmuyassarov, good to update the deps 👍 Good to go

/retitle Bump Kubernetes to v1.25.3
/lgtm

**Pull request merged**
