### PR TITLE
Drop support for hooks

### PR DESCRIPTION
**Pull request by ArangoGutierrez**

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
Thanks for working on this @ArangoGutierrez 

One nit about the commit message. The hooks have already been marked as deprecated so I think a better description would be "Drop support for hooks" or something.

Another comment: we should also drop the `source.d` mounts from kustomize and Helm deployments.

Otherwise looks good

**Comment by ArangoGutierrez** [comment]
> Thanks for working on this @ArangoGutierrez
> 
> One nit about the commit message. The hooks have already been marked as deprecated so I think a better description would be "Drop support for hooks" or something.
> 
> Another comment: we should also drop the `source.d` mounts from kustomize and Helm deployments.
> 
> Otherwise looks good

Done

**Comment by ArangoGutierrez** [comment]
Fixes #856

**Review by marquiz — COMMENTED** [review]
Ach, there's still some references to `source.d` in the customization guide in docs. If you could remove those, too.

**Comment by ArangoGutierrez** [comment]
> source.d

Done

**Pull request merged**
