### PR TITLE
go.mod: update deps

### PR DESCRIPTION
**Pull request by marquiz**
The gist of these updates is to update the opentelemetry packages to versions with the latest security fixes.

Supersedes #1419 and #1420 from @dependabot.

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by marquiz** [comment]
Let's wait for #1421 
/hold

**Comment by marquiz** [comment]
@ArangoGutierrez rebased, plus added  a commit that bumps k8s to v1.28.3

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
