### PR TITLE
test/e2e: drop host-usr-src mount

### PR DESCRIPTION
**Pull request by marquiz**
Allows running e2e-tests in some more restricted environments.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
hmm., I've had a successful run though on minikube with 1.25 k8s cluster...
e2e results
```
Ran 7 of 251 Specs in 162.396 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 244 Skipped
--- PASS: TestE2E (162.40s)
PASS
ok  	sigs.k8s.io/node-feature-discovery/test/e2e	162.445s

```
minikube version
```
$ minikube version
minikube version: v1.28.0
commit: 986b1ebd987211ed16f8cc10aed7d2c42fc8392f
```

k8s version
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marquiz** [comment]
> hmm., I've had a successful run though on minikube with 1.25 k8s cluster...

I used kvm2 driver. And docker as the runtime (🫤) because of corporate https(s) proxy causes problems in minikube with containerd and cri-o

**Comment by marquiz** [comment]
Could be also fixed in the particular case (with `rw` host root fs) with hostPath volume type `HostPathDirectoryOrCreate` but I'm not that fond of this solution as it mangles the host system directories, would file on ro filesystems and we shouldn't really need `/usr/src` for the e2e-tests (just a small gap in kconfig detection)

**Comment by fmuyassarov** [comment]
> > hmm., I've had a successful run though on minikube with 1.25 k8s cluster...
> 
> I used kvm2 driver. And docker as the runtime (🫤) because of corporate https(s) proxy causes problems in minikube with containerd and cri-o

tested on kvm2 driver and I could reproduce the issue + dropping `host-user-src` fixed the issue. I think this patch doesn't have any harm to the docker driver in minikube and instead fixes the possible ways of running E2E on minikube clusters. As such, I'm +1
/lgtm

**Pull request merged**
